spring:
  config:
    activate:
      on-profile: dev

---
spring:
  profiles: local

server:
  port: 8081

basic:
  datasource:
    url: jdbc:postgresql://localhost:5432/basic
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

---
spring:
  profiles: dev

#server:
#  port: 8080

basic:
  datasource:
    url: jdbc:postgresql://localhost:5432/basic
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver